### ISSUE TITLE
Release a git tag

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Launcher#156]
For the last release [3.0.5](https://github.com/StarcounterSamples/Launcher/commit/cd9e216809391c5079600bd49bbd2b8b85a12c39), a git tag was not created.

@alemoi can you create it according to the instructions? https://github.com/StarcounterSamples/AppStoreServer/wiki/How-to-publish-apps

When you do it, it will appear in https://github.com/StarcounterSamples/Launcher/releases

**Comment by alemoi** [comment]
Sure, will do that!

**Comment by alemoi** [comment]
Just fixed that. Thanks for reporting!
