### ISSUE TITLE
Use Object.observe and Array.observe shim

### ISSUE THREAD

**Issue by warpech** [StarcounterSamples/Launcher#157]
Use Object.observe and Array.observe shim in Launcher, so it gets a chance to run in Firefox and Edge.

Put the shims to Starcounter's `/sys/`

cc @malx122

**Comment by miyconst** [comment]
This won't help Launcher to work in other browsers. 

A `css-grid` shim and `puppet-dom-bind` notifier are required to make Launcher work in other browsers.

Closing the issue.

**Comment by miyconst** [comment]
As pointed out by @tomalec, css-grid can work in IE, and `dom-bind-notifier` can work with `Object.observe` + `Array.observe` shims.

FF still requires css-grid shim, but in IE it should work. Reopening the issue.

https://github.com/Juicy/juicy-tile-editor/issues/91

**Comment by tomalec** [comment]
Please not the `Object.observe` is being removed from chrome as well https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/12NbuZ4BB7A

**Comment by miyconst** [comment]
Thanks for noting that. The shims are now included in Launcher and should work in Chrome before we get `puppet-dom-bind-notifier`.

**Comment by miyconst** [comment]
Launcher works in IE, `juicy-tile-editor` has it's own issue. Closing this one.
