### ISSUE TITLE
CSS Grid Layout Support - contradictory directives

### ISSUE THREAD

**Issue by per-samuelsson** [StarcounterSamples/Launcher#171]
Relates to #145.

I see this

![image](https://cloud.githubusercontent.com/assets/2902045/11499512/e76187ac-9826-11e5-9856-8e7614910bee.png)

when I'm accessing `http://127.0.0.1:8080/launcher` in Chrome. I just pulled the latest launcher, and built it myself. No other apps are running.

Yet, [here](https://github.com/StarcounterSamples/Launcher#chrome-stable--dev-channel) on the ReadMe, I'm told: 

> Experimental Web Platform features - **disabled**

Whos advice should I follow?

**Comment by warpech** [comment]
Good catch! Readme is outdated. I will update it now.
