### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by tomalec** [StarcounterSamples/Launcher#175]
Today @malx122 told me that it's important.

The first step is to remove the forced prompt with message that CSS Grid is not supported (https://github.com/StarcounterSamples/Launcher/issues/145)

Especially, that IE was the first browser that supported CSS Grid ;)

Launcher may still face lots of problems with IE, like shadow DOM styling limitations.
But I think locking user totally, behind CSS Grid support is not fair ;)

**Comment by miyconst** [comment]
@tomalec is this issue a duplicate of https://github.com/StarcounterSamples/Launcher/issues/157?

**Comment by tomalec** [comment]
Well #157 was originally about `Object.observe` and `dom-bind-notifier`. To say that "we support IE" it might be not enough.

**Comment by miyconst** [comment]
Anyway, this issue can be closed, as Launcher now works in IE, and `juicy-tile-editor` has its own issue: https://github.com/Juicy/juicy-tile-editor/issues/91

**Comment by tomalec** [comment]
Thanks
