### ISSUE TITLE
Both applications appears on one screen

### ISSUE THREAD

**Issue by diliger** [StarcounterSamples/Launcher#190]
When multiple applications with similar name started launcher displays both of them.

I'v installed the Procurement application and have application named ProcurementStats,
when i navigate to ProcurementStats after Procurement then ProcurementStats turns visible but Procurement still appears on the screen.

Here is a screenshot:
![two applications on one screen](https://cloud.githubusercontent.com/assets/15857369/12300489/c3ae926e-ba2c-11e5-8de6-c4331e283aa8.png)

After some research such line of html was found (it checks for AppName.StartsWith):
![mathc-path](https://cloud.githubusercontent.com/assets/15857369/12300526/f0f74e0a-ba2c-11e5-8fed-f09973d5b5a6.png)

cc @miyconst

**Comment by miyconst** [comment]
Yeah.. this is quite an issue. I will fix that.

**Comment by miyconst** [comment]
Fixed.
